version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: husky
    versions:
    - 4.3.6
    - 4.3.8
    - 5.1.2
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.13.8
  - dependency-name: webpack-cli
    versions:
    - 4.3.1
    - 4.4.0
  - dependency-name: ioredis
    versions:
    - 4.19.4
  - dependency-name: webpack
    versions:
    - 4.44.2
  - dependency-name: joi
    versions:
    - 17.3.0
  - dependency-name: eslint-plugin-prettier
    versions:
    - 3.3.0
