version: '3.5'

services:
  db:
    image: postgres:9.6
    container_name: noder_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=sample_db
  redis:
    image: redis:4
    container_name: noder_redis
  web:
    image: noder_web
    container_name: noder_web
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./views:/app/views
      - ./static:/app/static
      - ./locales:/app/locales
    command: sh -c "npm run dev"
    ports:
      - "127.0.0.1:3000:3000"
    depends_on:
      - db
      - redis
      - migration
  migration:
    build:
      context: .
      target: base
    image: noder_web
    container_name: noder_migration
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - NODE_ENV=development
    volumes:
      - ./src:/app/src
      - ./views:/app/views
      - ./static:/app/static
      - ./locales:/app/locales
    command: sh -c "npm run knex -- migrate:latest"
    depends_on:
      - db
      - redis
volumes:
  pgdata:
